### ISSUE TITLE
lina send me your "back" function !

### ISSUE THREAD

**Issue by idanaroz** [wattad169/Playground#12]
1. send function that fix back button.
2. give idan function's name that deal with server.

**Comment by wattad169** [comment]
@idanaroz 
the back function: on your activity class add:
@Override
    public void onBackPressed()
    {
        super.onBackPressed();
/\* here set the activity that you want to open when pressed back*/
        Intent next = new Intent(getApplication(),MainActivity.class);
        startActivity(next);
        finish();
    }

**Comment by linaGitovich** [comment]
@idanaroz 
the app for the server : 
Google App Engine Launcher
