### ISSUE TITLE
Joining an event from eventinfo will make all the events in the list as playing

### ISSUE THREAD

**Issue by wattad169** [wattad169/Playground#29]

**Comment by linaGitovich** [comment]
i will check and fix this tomorrow

**Comment by idanaroz** [comment]
In addition need to be fix:
 In listFragment:
![Uploading 458803_10150736563379158_1413797400_o.jpg…]()

                            if user press the playing button, in order to cancel his participation

**Comment by idanaroz** [comment]
In addition need to be fix:
In listFragment:
     fix the functionality of playing button (if user want to cancel participation)
![screenshot_20160526-235159](https://cloud.githubusercontent.com/assets/18208996/15590059/571a6d36-239e-11e6-88cb-b84d3f4c1533.png)

**Comment by idanaroz** [comment]
(after i pressed playing for event : "Tennis with lina" from )

![screenshot_20160527-000406](https://cloud.githubusercontent.com/assets/18208996/15590129/aee95e50-239e-11e6-8662-cc5475da613f.png)

**Comment by idanaroz** [comment]
- [ ] fix: The creator can join his own event (E.g : "Friday Funjoya" event )
  @linaGitovich
