### ISSUE TITLE
fix action bar + menu view 

### ISSUE THREAD

**Issue by linaGitovich** [wattad169/Playground#32]
i have a nice ‪tutorial‬‏ to this :)

**Comment by wattad169** [comment]
Fix what? elaborate more

**Comment by linaGitovich** [comment]
fix his view..the UI
for example : i want that the menu will look like this:
![image](https://cloud.githubusercontent.com/assets/18166316/15570788/76fe648a-2340-11e6-8a4c-0fd1079d9207.png)
