### ISSUE TITLE
Edit Event: give the user the option to edit his event

### ISSUE THREAD

**Issue by wattad169** [wattad169/Playground#33]
Users events in the event list view should have an edit icon that direct to edit eventActivity

**Comment by idanaroz** [comment]
more info about it:

we will 4 categories of events:
1. accepted
2. Waiting for approval (to enable the feature which give the creator the power to select the member of   the event)
3. Decline (when the creator decline from new member to join the event)
4. edited (when we need the user approval for the change)
5. history events
