### ISSUE TITLE
Splash Symmetry progress bar

### ISSUE THREAD

**Issue by idanaroz** [wattad169/Playground#63]

**Comment by wattad169** [comment]
what does that mean Symmetry ?
https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=translation+symmetry+to+hebrew

**Comment by idanaroz** [comment]
look at the splash page when you open the app.
Does  everything seems aligned to the center ?
Personally i don't think so

**Comment by wattad169** [comment]
I think we should delete the progress bar from the splash, all the concept behind the splash activity is for loading.
